export default {
  Paris: [
    {
      id: 1,
      city: `Paris`,
      coordinates: [
        52.3109553943508,
        4.81309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Paris. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
    {
      id: 2,
      city: `Paris`,
      coordinates: [
        52.3209553943508,
        4.82309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
    {
      id: 3,
      city: `Paris`,
      coordinates: [
        52.3309553943508,
        4.83309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
    {
      id: 4,
      city: `Paris`,
      coordinates: [
        52.3409553943508,
        4.84309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
    {
      id: 5,
      city: `Paris`,
      coordinates: [
        52.3509553943508,
        4.85309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
    {
      id: 6,
      city: `Paris`,
      coordinates: [
        52.3609553943508,
        4.86309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
  ],
  Cologne: [
    {
      id: 7,
      city: `Cologne`,
      coordinates: [
        52.3709553943508,
        4.8309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Cologne. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
    {
      id: 8,
      city: `Cologne`,
      coordinates: [
        52.3909553943508,
        4.88309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
    {
      id: 9,
      city: `Cologne`,
      coordinates: [
        52.3909553943508,
        4.89309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
    {
      id: 10,
      city: `Cologne`,
      coordinates: [
        52.3009553943508,
        4.80309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
    {
      id: 11,
      city: `Cologne`,
      coordinates: [
        52.3109553943508,
        4.81309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
    {
      id: 12,
      city: `Cologne`,
      coordinates: [
        52.3209553943508,
        4.82309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
  ],
  Brussels: [
    {
      id: 13,
      city: `Brussels`,
      coordinates: [
        52.3309553943508,
        4.8309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Cologne. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
  ],
  Amsterdam: [
    {
      id: 14,
      city: `Amsterdam`,
      coordinates: [
        52.3909553943508,
        4.85309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
    {
      id: 15,
      city: `Amsterdam`,
      coordinates: [
        52.369553943508,
        4.85309666406198,
      ],
      name: `Wood and stone place`,
      type: `Private room`,
      rating: 3.2,
      price: 80,
      priceText: `night`,
      bookmark: true,
      images: [
        `img/apartment-01.jpg`,
        `img/room.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: false,
      bedrooms: 1,
      adults: 2,
      inside: [
        `Wi-Fi`,
        `Towels`,
        `Coffee machine`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Lolla`,
        status: ``,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
      ],
    },
    {
      id: 16,
      city: `Amsterdam`,
      coordinates: [
        52.3909553943508,
        4.929309666406198,
      ],
      name: `Canal View Prinsengracht`,
      type: `Apartment`,
      rating: 4.7,
      price: 132,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/apartment-02.jpg`,
        `img/apartment-01.jpg`,
        `img/room.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: false,
      bedrooms: 2,
      adults: 4,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
        `PS4`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Jenis`,
        status: `pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
      ],
    },
    {
      id: 17,
      city: `Amsterdam`,
      coordinates: [
        52.3809553943508,
        4.939309666406198,
      ],
      name: `Nice. cozy. warm big bed apartment`,
      type: `Apartment`,
      rating: 4.8,
      price: 180,
      priceText: `night`,
      bookmark: true,
      images: [
        `img/apartment-03.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-01.jpg`,
        `img/room.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 2,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
        `PS4`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Carmella`,
        status: `pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
      ],
    }
  ],
  Hamburg: [
    {
      id: 18,
      city: `Hamburg`,
      coordinates: [
        52.3709553943508,
        4.8309666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Cologne. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
  ],
  Dusseldorf: [
    {
      id: 19,
      city: `Dusseldorf`,
      coordinates: [
        52.3909553943508,
        4.8909666406198,
      ],
      name: `Beautiful &amp; luxurious apartment at great location`,
      type: `Apartment`,
      rating: 2,
      price: 120,
      priceText: `night`,
      bookmark: false,
      images: [
        `img/room.jpg`,
        `img/apartment-01.jpg`,
        `img/apartment-02.jpg`,
        `img/apartment-03.jpg`,
        `img/studio-01.jpg`,
        `img/apartment-01.jpg`,
      ],
      mark: true,
      bedrooms: 3,
      adults: 3,
      inside: [
        `Wi-Fi`,
        `Washing machine`,
        `Towels`,
        `Heating`,
        `Coffee machine`,
        `Baby seat`,
        `Kitchen`,
        `Dishwasher`,
        `Cabel TV`,
        `Fridge`,
      ],
      host: {
        avatar: `img/avatar-angelina.jpg`,
        name: `Angelina`,
        status: `Pro`,
      },
      description: [
        `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Cologne. The building is green and from 18th century.`,
        `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      ],
    },
  ],
};
