export default [
  {
    name: `Beautiful &amp; luxurious apartment at great location`,
    type: `Apartment`,
    rating: 4.8,
    price: 120,
    priceText: `night`,
    bookmark: false,
    images: [
      `img/room.jpg`,
      `img/apartment-01.jpg`,
      `img/apartment-02.jpg`,
      `img/apartment-03.jpg`,
      `img/studio-01.jpg`,
      `img/apartment-01.jpg`,
    ],
    mark: true,
    bedrooms: 3,
    adults: 3,
    inside: [
      `Wi-Fi`,
      `Washing machine`,
      `Towels`,
      `Heating`,
      `Coffee machine`,
      `Baby seat`,
      `Kitchen`,
      `Dishwasher`,
      `Cabel TV`,
      `Fridge`,
    ],
    host: {
      avatar: `img/avatar-angelina.jpg`,
      name: `Angelina`,
      status: `Pro`,
    },
    description: [
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
      `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
    ],
  },
  {
    name: `Wood and stone place`,
    type: `Private room`,
    rating: 4.5,
    price: 80,
    priceText: `night`,
    bookmark: true,
    images: [
      `img/apartment-01.jpg`,
      `img/room.jpg`,
      `img/apartment-02.jpg`,
      `img/apartment-03.jpg`,
      `img/studio-01.jpg`,
      `img/apartment-01.jpg`,
    ],
    mark: false,
    bedrooms: 1,
    adults: 2,
    inside: [
      `Wi-Fi`,
      `Towels`,
      `Coffee machine`,
      `Kitchen`,
      `Dishwasher`,
      `Cabel TV`,
      `Fridge`,
    ],
    host: {
      avatar: `img/avatar-angelina.jpg`,
      name: `Lolla`,
      status: ``,
    },
    description: [
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    ],
  },
  {
    name: `Canal View Prinsengracht`,
    type: `Apartment`,
    rating: 4.9,
    price: 132,
    priceText: `night`,
    bookmark: false,
    images: [
      `img/apartment-02.jpg`,
      `img/apartment-01.jpg`,
      `img/room.jpg`,
      `img/apartment-03.jpg`,
      `img/studio-01.jpg`,
      `img/apartment-01.jpg`,
    ],
    mark: false,
    bedrooms: 2,
    adults: 4,
    inside: [
      `Wi-Fi`,
      `Washing machine`,
      `Towels`,
      `Heating`,
      `Coffee machine`,
      `Baby seat`,
      `Kitchen`,
      `Dishwasher`,
      `Cabel TV`,
      `Fridge`,
      `PS4`,
    ],
    host: {
      avatar: `img/avatar-angelina.jpg`,
      name: `Jenis`,
      status: `pro`,
    },
    description: [
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    ],
  },
  {
    name: `Nice. cozy. warm big bed apartment`,
    type: `Apartment`,
    rating: 5,
    price: 180,
    priceText: `night`,
    bookmark: true,
    images: [
      `img/apartment-03.jpg`,
      `img/apartment-02.jpg`,
      `img/apartment-01.jpg`,
      `img/room.jpg`,
      `img/studio-01.jpg`,
      `img/apartment-01.jpg`,
    ],
    mark: true,
    bedrooms: 2,
    adults: 3,
    inside: [
      `Wi-Fi`,
      `Coffee machine`,
      `Baby seat`,
      `Kitchen`,
      `Dishwasher`,
      `Cabel TV`,
      `Fridge`,
      `PS4`,
    ],
    host: {
      avatar: `img/avatar-angelina.jpg`,
      name: `Carmella`,
      status: `pro`,
    },
    description: [
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
    ],
  }
];
